# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HackUTD' do

pod 'Parse'

end

target 'HackUTDTests' do

end

target 'HackUTDUITests' do

end

